name: Supabase Keep Alive

on:
  schedule:
    - cron: '0 0 * * *' # Berjalan otomatis setiap jam 12 malam
  workflow_dispatch:   # Tombol untuk menjalankan manual kapan saja

jobs:
  run-ping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kode
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install requests

      - name: Jalankan Script Ping
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python supabase_keep_alive.py
